name: .NET Format

on:
  pull_request
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Install dotnet format
      run: dotnet tool install -g dotnet-format
    - name: Execute dotnet-format
      run: dotnet-format . -f --include indiana-jones-desktop-adventures-ripper/
    - name: Add and commit changes
      uses: Endbug/add-and-commit@master
      with:
        author_name: Github Actions
        author_email: actions@github.com
        message: Automated dotnet-format update
        ref: ${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
