name: .NET Format

on:
  pull_request
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Install dotnet format
      run: dotnet tool install -g dotnet-format
    - name: Evaluate files changed
      run: git diff ${{ github.base_ref }}
    - name: Execute dotnet-format
      run: dotnet-format . -f --include indiana-jones-desktop-adventures-ripper/
