name: .NET Format

on:
  pull_request
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
       repository: ${{ github.event.pull_request.head.repo.full_name }}
       ref: ${{ github.event.pull_request.head.ref }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install jq
      run: sudo apt install jq
    - name: Install dotnet format
      run: dotnet tool install -g dotnet-format
    - name: Select Pull Request Id
      run: prid=$(echo ${{ github.ref }} | cut -d "/" -f 3)
    - name: Notify Pull Request Id
      run: echo "Processing PullRequest Id $prid"
    - name: Cosas ficheros
      run: curl -s -H "Accept: application/vnd.github.v3.raw+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/hefesto84/pr_label_action/${{ github.ref }}/files | jq -r '.[].filename' > files_changed.txt
    - name: Echooo
      run: cat files_changed.txt
    - name: Execute dotnet-format
      run: dotnet-format . -f --include indiana-jones-desktop-adventures-ripper/
    - name: Add and commit changes
      uses: Endbug/add-and-commit@v9.0.0
      with:
        author_name: Github Actions
        author_email: actions@github.com
        message: Automated dotnet-format update
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
